# Generated by Django 2.0.13 on 2019-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191202_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='brak', max_length=350),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
