# Generated by Django 2.0.13 on 2019-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191202_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order_products',
            name='product_id',
            field=models.ManyToManyField(to='shop.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
