# Generated by Django 2.0.13 on 2019-12-11 21:53

from django.db import migrations
import django_enumfield.db.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191211_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=shop.models.StatusField),
        ),
    ]
