# Generated by Django 2.0.13 on 2019-12-12 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20191212_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='shipment_adres',
            field=models.CharField(default='none', max_length=45),
        ),
        migrations.AddField(
            model_name='users',
            name='user_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
